name = "astrospacious"

# Pages build directory (required)
pages_build_output_dir = "./dist"

# KV bindings
[[kv_namespaces]]
binding = "topic-data"
id = "bb1be2087af6466fb8e995fa12648c1d"
preview_id = "bb1be2087af6466fb8e995fa12648c1d"